language: node_js
git:
  depth: 10
node_js:
  - "5"
  - "4.2"
  - "0.12"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"
  - "iojs-v1.0"
  - "iojs-v2.3"
  - "iojs-v3.3"
cache:
  bundler: true
  apt: true
  directories:
    - node_modules
notifications:
  email:
    on_success: never
    on_failure: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f5350a3bccfdf3d07867
sudo: required
branches:
  only:
    - compatibleTest
